version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.3
  clojure: lambdaisland/clojure@0.0.7

jobs:
  run-kaocha:
    parameters:
      os:
        type: executor
      clojure_version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - kaocha/execute:
                args: "--reporter documentation"
                clojure_version: << parameters.clojure_version >>
      - kaocha/upload_codecov

workflows:
  kaocha-test:
    jobs:
      - run-kaocha:
          matrix:
            parameters:
              os: [clojure/openjdk17, clojure/openjdk16, clojure/openjdk15, clojure/openjdk11]
              clojure_version: ["1.9.0", "1.10.3"]
