/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lambdaisland_funnel_Daemon */

#ifndef _Included_lambdaisland_funnel_Daemon
#define _Included_lambdaisland_funnel_Daemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lambdaisland_funnel_Daemon
 * Method:    daemonize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lambdaisland_funnel_Daemon_daemonize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
